### ISSUE TITLE
Trouble building on windows

### ISSUE THREAD

**Issue by antithing** [komrad36/KORAL#1]
Hi! And thanks for making this code available. I am trying to build on windows with the following cmake:
```

cmake_minimum_required(VERSION 2.8 FATAL_ERROR)
project(KORAL)

set(CMAKE_MACOSX_RPATH 1) # This is needed in macOS
set( CMAKE_BUILD_TYPE Release )


IF (!APPLE)
  set(CMAKE_CXX_COMPILER g++)
ENDIF()

set( CMAKE_CXX_FLAGS "-std=c++11" )

find_package(OpenCV REQUIRED)
IF (OpenCV_FOUND)
  message([message] OpenCV_VER:${OpenCV_VERSION})
  include_directories(${OpenCV_INCLUDE_DIRS})
  link_directories(${OpenCV_LIBRARY_DIRS})
  add_definitions(${OpenCV_DEFINITIONS})
ENDIF()



find_package(CUDA REQUIRED)
IF(CUDA_FOUND)
    SET(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};-O3 -gencode arch=compute_61,code=sm_61)
   
ENDIF()

include_directories(${CMAKE_SOURCE_DIR}/src ${CUDA_TOOLKIT_INCLUDE})

add_executable(
  KORAL
  src/main.cpp
  src/CLATCH.cu
  src/CLATCH.h
  src/CUDALERP.cu
  src/CUDALERP.h
  src/FeatureAngle.h
  src/Keypoint.h
  src/KFAST.h
  src/KORAL.h
  )

target_link_libraries(
  KORAL
  ${OpenCV_LIBS}
  ${CUDA_LIBRARIES})


```

And the project will not compile, giving me:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "void __cdecl CLATCH(unsigned __int64 * const,unsigned __int64,struct Keypoint const * __restrict const,int,unsigned __int64 * __restrict const)" (?CLATCH@@YAXQEA_K_KQEIBUKeypoint@@HQEIA_K@Z) referenced in function "public: void __cdecl KORAL::go(unsigned char const *,unsigned int,unsigned int,unsigned char)" (?go@KORAL@@QEAAXPEBEIIE@Z)	KORAL	X:\dev\Features\KORAL\built\main.obj	1	
```
and:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "void __cdecl CUDALERP(unsigned __int64,float,float,unsigned char * __restrict const,unsigned __int64,unsigned int,unsigned int,struct CUstream_st * const)" (?CUDALERP@@YAX_KMMQEIAE0IIQEAUCUstream_st@@@Z) referenced in function "public: void __cdecl KORAL::go(unsigned char const *,unsigned int,unsigned int,unsigned char)" (?go@KORAL@@QEAAXPEBEIIE@Z)	KORAL	X:\dev\Features\KORAL\built\main.obj	1	
```

Where am i going wrong here? 

Thank you.

**Comment by MikePelton** [comment]
Hi antithing - can't solve your cmake problem but by freaky coincidence have just built this code under Visual Studio 2017 against CUDA 10 and it works very well out of the box. All I did was File->New Project->NVidia->CUDA 10.0, removed the default kernel.cu from the project, added in komrad36's files and hit build. It is very hard to achieve that kind of ease of build in C++!!
For your problem the linker is complaining it can't find the functions from CLATCH.cu and the other "cu" kernel definitions. I don't speak cmake but I wonder if you have to explicitly include clatch.obj  etc in the final statement?

**Comment by antithing** [comment]
Hi! thanks for your reply. I can never get the cuda toolkit to install vs integration without crashing! Can create a regular project and then add CUDA to it?

**Comment by antithing** [comment]
aha! Based on this:

https://www.olegtarasov.me/how-to-build-cuda-toolkit-projects-in-visual-studio-2017/

I have it working. needed to get vs integration, then set the file type of the .cu files to `C++/CUDA`
